services:
  - type: web
    name: food-hub-backend
    env: node
    plan: free
    buildCommand: npm install && prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: BETTER_AUTH_URL
        value: https://food-hub-backend.onrender.com
